// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiyvGn8Aoc0NnRXpfJsBKkWUVqgWV_G38',
    appId: '1:831991617606:web:3d183b71785d10f4e11247',
    messagingSenderId: '831991617606',
    projectId: 'diary-b0ac3',
    authDomain: 'diary-b0ac3.firebaseapp.com',
    storageBucket: 'diary-b0ac3.appspot.com',
    measurementId: 'G-KCPKGRD5Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOs2WWDVYlgWY-_WGJi3eoHhLimlrXOg0',
    appId: '1:831991617606:android:79cdb7aea24558c8e11247',
    messagingSenderId: '831991617606',
    projectId: 'diary-b0ac3',
    storageBucket: 'diary-b0ac3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfUyZ2sApO1XSwuX74ERasbOLsXbTE4f0',
    appId: '1:831991617606:ios:0b309e0487f66b5de11247',
    messagingSenderId: '831991617606',
    projectId: 'diary-b0ac3',
    storageBucket: 'diary-b0ac3.appspot.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfUyZ2sApO1XSwuX74ERasbOLsXbTE4f0',
    appId: '1:831991617606:ios:0b309e0487f66b5de11247',
    messagingSenderId: '831991617606',
    projectId: 'diary-b0ac3',
    storageBucket: 'diary-b0ac3.appspot.com',
    iosBundleId: 'com.example.diaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiyvGn8Aoc0NnRXpfJsBKkWUVqgWV_G38',
    appId: '1:831991617606:web:410831ed214e1afbe11247',
    messagingSenderId: '831991617606',
    projectId: 'diary-b0ac3',
    authDomain: 'diary-b0ac3.firebaseapp.com',
    storageBucket: 'diary-b0ac3.appspot.com',
    measurementId: 'G-874B4L6MS0',
  );
}
